name: keepalive

on:
  workflow_dispatch:
  schedule:
    - cron: 0 13 1,15 * *

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
    - name: Set time zone
      run: | 
        sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: Update keepalive
      run: | 
        repos="backup hostloc-auto-get-points BiliBiliTool TiebaSignIn" #仓库名称
        str=$(date)%0D%0A%0D%0A
        str=$(echo $str | sed "s/\ /%20/g")
        str=$(echo $str | sed "s/:/%3A/g")
        for repo in $repos
        do
        git clone https://github.com/${GITHUB_ACTOR}/${repo}
        cd ${repo}
        echo "$(date)" > keepalive
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add keepalive
        git commit -m "Update keepalive" -a
        git push "https://${GITHUB_ACTOR}:${{ secrets.PAT }}@github.com/${GITHUB_ACTOR}/${repo}.git"
        str=${str}${repo}保活成功%0D%0A%0D%0A
        cd ..
        done
        echo "PUSHSTR=${str}" >> $GITHUB_ENV
    - name: Push
      run: | 
        if [ "${{ secrets.PUSH_SCKEY }}" != "" ];then
        curl -d "text=keepalive" -d "desp=${PUSHSTR}" -X POST  https://sctapi.ftqq.com/${{ secrets.PUSH_SCKEY }}.send
        fi
