name: Update_personal_actions

on: 
  push: 
    branches: 
      - main
    paths-ignore:
      - 'keepalive'
  workflow_dispatch: 

jobs:
  Update_personal_actions:
    runs-on: ubuntu-latest
    steps:
    - name: Set time zone
      run: | 
        sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: Update_script
      run: | 
        folders="py others" # 要更新的文件夹名称
        git clone https://github.com/${{ github.actor }}/backup
        git clone https://github.com/${{ github.actor }}/personal_actions
        for folder in $folders
        do
        rm -rf personal_actions/${folder}/*
        cp -arf backup/${folder}/. personal_actions/${folder}
        done
    - name: Update_workflows
      run: | 
        rm -rf personal_actions/.github/workflows/*
        cp -arf backup/workflows/. personal_actions/.github/workflows
    - name: Update_.gitignore
      run: | 
        rm -rf personal_actions/.gitignore
        cp -arf backup/.gitignore personal_actions
    - name: commit & push
      run: | 
        cd personal_actions
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add .
        {
        git commit -m "Update_personal_actions" -a && git push "https://${{ github.actor }}:${{ secrets.GH_PAT }}@github.com/${{ github.actor }}/personal_actions.git"
        } || { 
        echo "没有找到更改"
        }
